# Generated by Django 5.2.17 on 2026-09-17 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, default='queued', max_length=80)),
                ('current_year', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('result_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('wellpad', 'Кустовая площадка'), ('facility', 'Объект подготовки'), ('delivery-point', 'Точка поставки')], max_length=32)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('width_m', models.FloatField(default=140.0)),
                ('height_m', models.FloatField(default=100.0)),
                ('angle_deg', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('running', 'Работает'), ('warning', 'Предупреждение'), ('stopped', 'Остановлен')], default='running', max_length=32)),
                ('license_area', models.CharField(blank=True, default='', max_length=255)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Новый проект', max_length=255)),
                ('slug', models.SlugField(default='default', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('storage_crs', models.CharField(default='EPSG:4326', max_length=40)),
                ('source_crs', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('data', models.JSONField(default=dict)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_results', to='core.facility')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gr_results', to='core.calculationrun')),
            ],
            options={
                'ordering': ['year', 'entity_id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('vertex', 'Вершина ребра'), ('tee', 'Тройник'), ('tap', 'Врезка')], default='vertex', max_length=16)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='core.facility')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.project')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('fluid', models.CharField(choices=[('oil', 'Нефть'), ('gas', 'Газ'), ('water', 'Вода')], default='oil', max_length=8)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('diameter_mm', models.FloatField(blank=True, null=True)),
                ('wall_thickness_mm', models.FloatField(blank=True, null=True)),
                ('roughness_mm', models.FloatField(blank=True, null=True)),
                ('burial_depth_m', models.FloatField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_segments', to='core.networknode')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_segments', to='core.networknode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.project')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('fluid', models.CharField(choices=[('oil', 'Нефть'), ('gas', 'Газ'), ('water', 'Вода')], default='oil', max_length=8)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='core.project')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LicenceArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_areas', to='core.project')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow_type', models.CharField(default='Нефтепровод', max_length=120)),
                ('fluid', models.CharField(blank=True, choices=[('oil', 'Нефть'), ('gas', 'Газ'), ('water', 'Вода')], default='', max_length=8)),
                ('is_logical_flow', models.BooleanField(default=False)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='core.facility')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='core.facility')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.project'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_runs', to='core.project'),
        ),
        migrations.CreateModel(
            name='ValidationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('ok', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_items', to='core.facility')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PipelineSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_segments', to='core.pipeline')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_memberships', to='core.networksegment')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('pipeline', 'position'), name='uq_pipeline_position'), models.UniqueConstraint(fields=('pipeline', 'segment'), name='uq_pipeline_segment')],
            },
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key__isnull', False)), fields=('project', 'external_key'), name='uq_pipeline_project_external'),
        ),
        migrations.AddConstraint(
            model_name='networksegment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key__isnull', False)), fields=('project', 'external_key'), name='uq_segment_project_external'),
        ),
        migrations.AddConstraint(
            model_name='networknode',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key__isnull', False)), fields=('project', 'external_key'), name='uq_node_project_external'),
        ),
        migrations.AddConstraint(
            model_name='licencearea',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key__isnull', False)), fields=('project', 'external_key'), name='uq_area_project_external'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key__isnull', False)), fields=('project', 'external_key'), name='uq_facility_project_external'),
        ),
    ]
