# Generated by Django 5.2.17 on 2026-09-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='bound_fitting_external',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networknode',
            name='bound_tap_external',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networknode',
            name='tap_edge_external',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networknode',
            name='tap_t',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
